# Generated by Django 5.0.2 on 2024-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('PAID', 'Оплачен'), ('PROCESSING', 'В процессе'), ('DELIVERY', 'Доставляется'), ('FINISHED', 'Доставлен'), ('CANCELLED', 'Отменен')], default='CREATED', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('PAID', 'Оплачен'), ('PROCESSING', 'В процессе'), ('DELIVERY', 'Доставляется'), ('FINISHED', 'Доставлен'), ('CANCELLED', 'Отменен')], max_length=30)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
